container:
  image: golang:latest
  additional_containers:
    - name: splunk
      image: imdhruva/splunk:latest
      port: 8089

task:
  name: lint
  lint_script: gofmt -d ./*.go

task:
  name: check_splunk_available
  splunk_available_script: splunk_status=$(docker container ls -q -f "name=splunk");[[ -n $splunk_status ]] && exit 1

task:
  name: test
  code_script: go test
  depends_on:
    - lint
    - check_splunk_available
